name: "telegram-desktop-patched"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: mycache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
